### PR TITLE
Updated Red Hat info

### PR DESCRIPTION
**Pull request by hbelmiro**
**What this PR does / why we need it**:

Fixes: https://github.com/serverlessworkflow/serverlessworkflow.github.io/issues/185

### CODE REVIEW

**Comment by hbelmiro** [comment]
@ricardozanini can you take a look?

**Comment by hbelmiro** [comment]
@tsurdilo can you please take a look?
This PR is important to update how Red Hat participates in Serverless Workflow, which doesn't includes business automation anymore. The Serverless Workflow implementation is a different project inside Kogito.

https://kiegroup.github.io/kogito-docs/serverlessworkflow/latest/index.html

**Comment by hbelmiro** [comment]
@tsurdilo can you have a look at this one too?

**Comment by ricardozanini** [comment]
@tsurdilo can you please merge? Thanks!

**Comment by tsurdilo** [comment]
hi sorry looking

**Review by tsurdilo — APPROVED** [review]

**Pull request merged**
